PipelineSecrets:
  DockerConfig: '{"auths": {"docker-registry.default.svc:5000": {"auth": "c2VydmljZWFjY291bnQ6ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSjkuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSnFlQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUpxWlc1cmFXNXpMWGd0Y21WbmFYTjBjbmt0ZEc5clpXNHRlSGhqYldjaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaWFtVnVhMmx1Y3kxNExYSmxaMmx6ZEhKNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU9UazVZVFE1WVRrdFpqVmlaUzB4TVdVNUxXSTNaRE10T1RZd01EQXdNbVUxTldSaElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXA0T21wbGJtdHBibk10ZUMxeVpXZHBjM1J5ZVNKOS5PY1ZOSi0tOXk5MHFiWXBoaHJYRVczdVdFVWNMTFNkSnloZmwyZUk1MmdnTjVHN0d6blVsM2JDUkIydkZvT1VLWDNGMC1MUHRmR1QxRndKVGUwWjFFck1HTkpLdFhiU1JOeG9GbTh2ay1lN1g3OEhsWVFqSWlVbmE3U1NZOUx3Z2FQMjhLSnd5Z2FLenZ5N0o2ZG4ya0RpVldtWTlUMTdZNU1LaHBBd1E0Vmwydm9CN0hpNW9xVll4NFZRblVad0FZWl9JeGw5VzlZbXN2Y2JDcDRxNnE4Xy1sQ1JzWHdVMmZBa1pIWHR0YS13b3kxSENCMzVvTjNrR0ExTzRtRTZUYU55bDVKRDVnNUNfM29jYkdDRER0U3FtWDRBNjNlalFlbE9Sd25kZ1UwYlh3Z1JGbmFSRW1JRXpvdWwtU2JhNG5JZFRfVXRvY1dUb3huLU1IdlpZeFE="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: apps.wheel.sh
    exposer: Route
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: docker-registry.default.svc:5000
        TILLER_NAMESPACE: kube-system
prow: {}
